### PR TITLE
WIP: Oracle 19c 19.3

### PR DESCRIPTION
**Pull request by SamDesmondKing**
This is a WIP as I haven't figured out how to automate the population of the database after it's pulled down from docker hub. I'm finding that the tools provided to do this don't work as expected. Progress today has been working out how to populate it manually, and rewriting the SQL to comply with oracle's flavor. 

---

Issues so far

Oracle doesn't provide a pre-built 21c-xe docker image. We need to build it ourselves, and host it on docker hub. 

There is a pre-built image for enterprise versions of the software, but it requires payment and authenticating against docker to pull it down.

The resources to build these images, and documentation on them are found [here](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-scripts-after-setup-and-on-startup).
 
Mounting the SQL script to this directory should mean it's automatically run when the container starts for the first time"
`./sql/create_database.sql:/opt/oracle/scripts/setup/create_database.sql`
As per [this doc](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-scripts-after-setup-and-on-startup). 
However, this doesn't work.

Also, setting the following env var
`ORACLE_PASSWORD=Dev1234`
Should automatically set the password for the users SYS, SYSTEM, etc. This also doesn't work. The environment variable is present in the container but is the incorrect password for these users.

---

Because of the above issues, to populate the database we need to manually connect at the CMD level as the root user, change the password for SYS, then connect to the default PDB (XEPDB1), then run the SQL script manually as this user. Here are the steps.

Connect to the container
`docker exec -it --user=oracle oracle-21c-xe_oracle_1 bash`

Connect to the root CBD
`sqlplus / as sysdba`

Change the password for SYS
`ALTER USER SYS IDENTIFIED BY Dev1234 ACCOUNT UNLOCK;`

Connect to the default PDB with the new password
`sqlplus SYS/Dev1234@XEPDB1 AS SYSDBA`

Run the script, which creates tables, adds data and creates the tidal user
`@/opt/oracle/scripts/setup/create_database.sql`

After this is done you can connect to the PDB with the user created for tidal tools, using the following command:

`sqlplus tidal/Dev1234@XEPDB1`

User: tidal
Password: Dev1234
Database (PDB) name: XEPDB1

### CODE REVIEW

**Comment by prees1** [comment]
Great work on these docker setups Sam!

Oracle is tricky and not great to work with. Don't worry its not just you in having issues in using it!


For building the images. We could include the Dockerfile that you are building and using for the image here in the repo, that way it can all be reproduced and configured from here. docker-compose has a `build` key too that lets you specify a dockerfile to build and use, so it can all be sourced and controlled from the repo, without depending on a registry/dockerhub to set it up.

On the password, is it possible that the env var is `$ORACLE_PWD`, I see that one referenced in there dockerfile and scripts - https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh#L13


On the volume mounting, I was wondering, did you try mounting a dir from the host, that has the file in it, to their specified dir. something like: `./sql:/opt/oracle/scripts/setup/` in the docker compose config and then on the host there is a file at

`./sql/create_database.sql`

I think I've seen that before with docker volume mounts, treating files vs directories differently depending on whats mapped to what.


If those are all dead ends too. I will say, having what you have here is way ahead of what we have today (nothing!). And having it mostly automated with a few commands that are scripted/copy&pasted. still gets you all to a very efficient way to creating reproducible dbs and setups for testing, validation, etc.

**Comment by prees1** [comment]
Great work on these docker setups Sam!

Oracle is tricky and not great to work with. Don't worry its not just you in having issues in using it!


For building the images. We could include the Dockerfile that you are building and using for the image here in the repo, that way it can all be reproduced and configured from here. docker-compose has a `build` key too that lets you specify a dockerfile to build and use, so it can all be sourced and controlled from the repo, without depending on a registry/dockerhub to set it up.

On the password, is it possible that the env var is `$ORACLE_PWD`, I see that one referenced in there dockerfile and scripts - https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh#L13


On the volume mounting, I was wondering, did you try mounting a dir from the host, that has the file in it, to their specified dir. something like: `./sql:/opt/oracle/scripts/setup/` in the docker compose config and then on the host there is a file at

`./sql/create_database.sql`

I think I've seen that before with docker volume mounts, treating files vs directories differently depending on whats mapped to what.


If those are all dead ends too. I will say, having what you have here is way ahead of what we have today (nothing!). And having it mostly automated with a few commands that are scripted/copy&pasted. still gets you all to a very efficient way to creating reproducible dbs and setups for testing, validation, etc.

**Comment by SamDesmondKing** [comment]
Hey @prees1 thanks for taking a look! Yeah it definitely seems to be the hardest DB for this task so far. Excellent point on `ORACLE_PWD` - I actually spotted that too in another repo and tried it but no luck.

I'll give the directory mount a go today as well as trying to find a way around the password issue. If there's still no luck, on Friday we discussed pivoting to a different solution, where we manually spin up the database, fill it with demo data then create an AMI in riptide ca-central-1 from that machine. That way we can simply spin up machines from that AMI and the database + demo data is there without needing to fight oracle to automate it.

**Comment by SamDesmondKing** [comment]
@prees1 Thank you for the suggestion to include the dockerfile! That worked a treat.

**Comment by prees1** [comment]
cool! git lfs comes to mind.

Do we have this repo tied to a slack channel yet, for event notifications?

**Pull request closed without merging**
